// src/constants/screenNames.ts
enum ScreenNameEnum {
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  LANGUAGE_SELECT = 'LANGUAGE_SELECT',
  PhoneLogin = 'PhoneLogin',
  OTPVerification = 'OTPVerification',
  UserInfoForm = 'UserInfoForm',
  TabNavigator = 'TabNavigator',
  JobDetailsScreen = 'JobDetailsScreen',
  NotificationList = 'NotificationList',
  JobInvoiceScreen = 'JobInvoiceScreen',
  ReferToEarnScreen = 'ReferToEarnScreen',
  HowToUseScreen = 'HowToUseScreen',
  HelpSupportScreen = 'HelpSupportScreen',
  BookingTrackScreen = 'BookingTrackScreen',
  LocationFetcher = 'LocationFetcher',
  WalletScreen = 'WalletScreen',
  ReviewBookingScreen = 'ReviewBookingScreen',
  AddressesScreen = 'AddressesScreen',
  LocationPickerScreen = 'LocationPickerScreen',
  PaymentScreen = 'PaymentScreen',
  BookingDetailsScreen = 'BookingDetailsScreen',
  InvoiceScreen = 'InvoiceScreen',
  Feedback = 'Feedback',
  AllServicesScreen = 'AllServicesScreen',
  ServiceBookingScreen = 'ServiceBookingScreen',
  ArrivalChargesScreen = 'ArrivalChargesScreen',
  PoliciesScreen = 'PoliciesScreen',
  NearbyProvidersScreen = 'NearbyProvidersScreen',
  ApplyCouponScreen = 'ApplyCouponScreen',
  RecurringBookingScreen = 'RecurringBookingScreen',
}

export default ScreenNameEnum;
