// src/constants/screenNames.ts
enum ScreenNameEnum {
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  LANGUAGE_SELECT = 'LANGUAGE_SELECT',
  PhoneLogin = 'PhoneLogin',
  OTPVerification = 'OTPVerification',
  PartnerInfoForm = 'PartnerInfoForm',
  PartnerServiceSelectionScreen = 'PartnerServiceSelectionScreen',
  TabNavigator = 'TabNavigator',
  PartnerDocumentsScreen = 'PartnerDocumentsScreen',
  JobDetailsScreen = 'JobDetailsScreen',
  NotificationList = 'NotificationList',
  JobInvoiceScreen = 'JobInvoiceScreen',
  ReferToEarnScreen = 'ReferToEarnScreen',
  HowToUseScreen = 'HowToUseScreen',
  HelpSupportScreen = 'HelpSupportScreen',
  BookingTrackScreen = 'BookingTrackScreen',
  LocationFetcher = 'LocationFetcher',
  WalletScreen = 'WalletScreen',
  ReferralScreen = 'ReferralScreen',
  ReviewBookingScreen = 'ReviewBookingScreen',
  AddressesScreen = 'AddressesScreen',
  LocationPickerScreen = 'LocationPickerScreen',
  PaymentScreen = 'PaymentScreen',
  BookingDetailsScreen = 'BookingDetailsScreen',
  InvoiceScreen = 'InvoiceScreen',
  Feedback = 'Feedback',
}

export default ScreenNameEnum;
